version: '3'

services:
  web:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Running initial setup...';
      echo 'Installing composer packages...';
      composer install;
      echo 'Migrating database...';
      php bin/console doctrine:migrations:migrate --no-interaction;
      php bin/console -e test doctrine:database:create --no-interaction;
      php bin/console -e test doctrine:migrations:migrate --no-interaction;
      echo 'Loading Fixtures...';
      php bin/console doctrine:fixtures:load --no-interaction;
      echo 'Setup Completed';
      exec php-fpm;"
    networks:
      - omego

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - web
      - database
    networks:
      - omego

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - omego
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-app}
      interval: 10s
      retries: 10

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  omego:
    driver: bridge